# Generated by Django 2.2.3 on 2019-07-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_project_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
