# Generated by Django 2.2.3 on 2019-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20190716_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
